### PR TITLE
Add Traditional Chinese support

### PR DESCRIPTION
**Pull request by yelandiealma**
- Update Localization.cs to include Traditional Chinese
- Add zh-hant.json for Traditional Chinese translations
- Add zh-hant.json.meta file for metadata

### CODE REVIEW

**Comment by bdunderscore** [comment]
Thanks for the PR! I plan on finding a proper translation maintenance platform soon, as I don't think it'll be sustainable long-term to have ad-hoc PRs (in particular, Korean translations are quite incomplete right now, and it seems I've missed a few in ja-JP as well...)

I'll let you know when that's ready, and you can import your translations there at that time.

**Comment by yelandiealma** [comment]
I'm not sure if you need some advice or not, but I personally recommend https://crowdin.com/
By the way, the translation of VRChat is also done there.

**Comment by bdunderscore** [comment]
Thanks, that is helpful - I was looking at tolgee as well, so I'll compare the two a bit

**Comment by bdunderscore** [comment]
I'm not able to push to your main branch to update this PR to resolve conflicts, so I'll go ahead and merge this manually.

**Pull request merged**
